
=== Reading and writing audio data

The functions described in this section are available only in the 
<<jack.process_callback, process callback>>, and allow to read and write
samples from/to ports of the default audio type.

For this type of ports, a sample is represented by a Lua number.

////
@@ custom ports
- For custom ports a sample is a binary strings whose length is the 'buffer_size'
  passed as argument to port() when the port was created (the script can 
  handle them with string.pack() and string.unpack()).
////


[[audiojack.get_buffer]]
* *jack.get_buffer* ( _port_ ) _P_ +
-> _nframes_ +
[small]#Retrieves the port buffer and initializes the buffer's _current position_ to the first
sample. +
Returns the buffer size in samples (which is the same value as the _nframes_
parameter passed to the process callback). +
This function must be invoked in the <<jack.process_callback, process callback>>, at each
process cycle, before any other operation on the buffer.#

[[audiojack.raw_buffer]]
* *jack.raw_buffer* ( _port_ ) _P_ +
-> _pointer_, _nframes_ +
[small]#Returns the port buffer pointer (as a _light userdata_) and the number of frames.
It can be used only after having retrieved the buffer with <<audiojack.get_buffer, jack.get_buffer>>().#

[[audiojack.seek]]
* *jack.seek* ( _port_ [, _position_ ] ) _P_ +
-> _position_, _available_ +
[small]#Returns the current _position_ in the port's buffer and the number of available
samples from the current position to the end of the buffer. +
If _position_ is passed as argument, the function sets the current position to that value.#


[[audiojack.read]]
* *jack.read* ( _port_ [, _count_ ] ) _P_ +
-> _sample1_, _..._ +
[small]#Returns up to _count_ samples from the (input) port buffer. +
Samples are read starting from the current position, which is then advanced by the
number of returned samples. +
If _count_ exceeds the available samples, this function returns the available samples
only. If no samples are available, it returns _nil_. +
If _count_ is not passed, it defaults to _'all the remaining samples'_.#


[[audiojack.write]]
* *jack.write* ( _port_ [, _sample1_ , _..._ ] ) _P_ +
-> _count_ +
[small]#Writes the passed samples to the (output) port's buffer and returns the _count_ of 
written samples. +
Samples are written starting from the current position, which is then advanced by _count_.
If the number of passed samples exceeds the available space in the buffer, the exceeding
samples are discarded.#


[[audiojack.clear]]
* *jack.clear* ( _port_ [, _count_ ] ) _P_ +
-> _count_ +
[small]#Same as <<audiojack.write, jack.write>>(), with the difference that it writes up to _count_ 
samples to zero. +
If _count_ is not passed, it defaults to _'all the remaining samples'_.#



[[audiojack.copy]]
* *jack.copy* ( _dstport_, _srcport_ [, _count_ ] ) _P_ +
-> _count_ +
[small]#Copies up to _count_ samples from the buffer of the input port _srcport_ to the
buffer of the output port _dstport_ and returns the number of copied samples. +
This function uses the current positions of both ports, and advances them by the
number of copied samples. +
If _count_ is not passed, it defaults to _maxcount_, which is defined as the
minimum between the remaining samples in the input port's buffer and the space
left in the output port's buffer. +
If count is passed but it is greater than _maxcount_, only _maxcount_ samples
are copied.#



//^ -------------------------------------------------------------------------------

=== Reading and writing MIDI data

[small]#Rfr: link:++http://jackaudio.org/api/group__MIDIAPI.html++[Reading and writing MIDI data]#

The functions described in this section are available only in the 
<<jack.process_callback, process callback>>, and allow to read and write
MIDI events from/to ports of the default MIDI type.

[[midi_event]]
A MIDI event is represented in LuaJack as a couple of values (_time_, _data_), where:
[circles]
- _time_ is the frame number of the event, relative to the current period, and
- _data_ is a binary string of length >= 1, containing the MIDI message (_<status>..._).

The _data_ value may be handled with Lua's native 
http://www.lua.org/manual/5.3/manual.html#pdf-string.pack[string.pack]() and 
http://www.lua.org/manual/5.3/manual.html#pdf-string.pack[string.unpack]() functions,
or with the utilities provided in the <<midi_utilities, luajack/midi.lua>> module.


[[midijack.get_buffer]]
* *jack.get_buffer* ( _port_ ) _P_ +
-> _eventcount_, _lostcount_ (if port is input) +
-> _space_ (if port is output) +
[small]#Retrieves the port buffer. +
If _port_ is an input port, this function returns the number of events in the buffer
(_eventcount_) and the number of lost events (_lostcount_).
It also initializes the current index to _0_, i.e. to the first event in the buffer. +
If _port_ is an output port, the function returns the _space_ available in the buffer for 
writing MIDI event data. +
This function must be invoked in the <<jack.process_callback, process callback>>, at each
process cycle, before any other operation on the buffer.#


[[midijack.seek]]
* *jack.seek* ( _port_ [, _index_ ] ) _P_ +
-> _index_, _available_ +
[small]#Returns the current _index_ in the (input) port buffer and the number of _available_
events from the current index to the end of the buffer. +
If _index_ is passed as argument, sets the current index to that value.#

NOTE: Only input MIDI ports are seekable (output MIDI ports are not).


[[midijack.read]]
* *jack.read* ( _port_ [, _index_ ] ) _P_ +
-> _time_, _data_ +
[small]#Returns the <<midi_event, MIDI event>> from the (input) port's buffer at its current index, 
which it then advances by _1_. +
If an _index_ is passed as argument, this function sets the current index to that value
before reading the event. If the current index exceeds _eventcount - 1_, the function
returns _nil_.#


[[midijack.write]]
* *jack.write* ( _port_, _time_, _data_ ) _P_ +
-> _space_ +
[small]#Writes a <<midi_event, MIDI event>> to the (output) port's buffer and returns the _space_ 
available in the buffer for the next event data.
If there is not enough space to write the event, this function returns _nil_.#


[[midijack.copy]]
* *jack.copy* ( _dstport_, _srcport_ [, _count_ ] ) _P_ +
-> _count_ +
[small]#Copies up to _count_ <<midi_event, MIDI events>> from the buffer of the input port 
_srcport_  to the buffer of the output port _dstport_, and returns the number of copied events.
Events are copied starting from the current index of _srcport_, which is then
advanced by the number of copied events. +
If _count_ is not passed, this function attempts to copy all of the remaining events
in the input port's buffer that fit in the output port's buffer.#


