
=== Non real-time callbacks

[small]#Rfr: link:++http://jackaudio.org/api/group__ClientCallbacks.html++[Setting Client Callbacks].#

The functions listed here are available only in the <<luajack.contexts, main context>>
and can be used to register (Lua) callbacks for JACK events other than those that are
handled in the real-time audio processing thread.

The registered callbacks are also executed by LuaJack in the main context. Notice
that each callback receives the affected _client_ as its first argument (this is
because the main context is shared by all the clients created by the LuaJack application).

NOTE: All the non real-time Lua callbacks described here are executed by LuaJack in
the main pthread. JACK itself may execute its C callbacks in different pthreads; this
is a libjack implementation choice and may differ across different implementations as
well as platforms. When JACK executes a C callback, LuaJack saves the event associated
with it and promptly returns. The event is then translated in a Lua callback in the 
main pthread.

////
LuaJack callbacks and the functions to set them map (almost) one-to-one to 
http://jackaudio.org/api/group__ClientCallbacks.html[JACK callbacks] and are subject
the same considerations and constraints described in the JACK documentation.
////


[[jack.shutdown_callback]]
* *jack.shutdown_callback* ( _client_, _func_ ) _M_ +
[small]#Registers _func_ as callback for the 'shutdown' event. +
The callback is executed as *_func(client, code, reason)_*, where _code_ is a string
version of the JackStatus flags and _reason_ is a string describing the shutdown reason.
The callback need not be implemented as a signal handler (it may print, release resources
etc.).#


[[jack.freewheel_callback]]
* *jack.freewheel_callback* ( _client_, _func_ ) _M_ +
[small]#Registers _func_ as callback for the 'starting or stopping freewheel mode' event. +
The callback is executed as *_func(client, operation)_*, where _operation_ is a string
that may be either _'starting'_ or _'stopping'_.#


[[jack.sample_rate_callback]]
* *jack.sample_rate_callback* ( _client_, _func_ ) _M_ +
[small]#Registers _func_ as callback for the 'sample rate change' event. +
The callback is executed as *_func(client, nframes)_*, where _nframes_ is the new
sample rate.#


[[jack.client_registration_callback]]
* *jack.client_registration_callback* ( _client_, _func_ ) _M_ +
[small]#Registers _func_ as callback for the 'client (de)registration' event. +
The callback is executed as *_func(client, name, operation)_*, where _name_ is the name
of the affected client and _operation_ is a string that may be either _'registered'_ 
or _'unregistered'_.#


[[jack.port_registration_callback]]
* *jack.port_registration_callback* ( _client_, _func_ ) _M_ +
[small]#Registers _func_ as callback for the 'port (de)registration' event. +
The callback is executed as *_func(client, portname, operation)_*, where _portname_ is
the (full) name of the affected port and _operation_ is a string that may be 
either _'registered'_ or _'unregistered'_.#


[[jack.port_rename_callback]]
* *jack.port_rename_callback* ( _client_, _func_ ) _M_ +
[small]#Registers _func_ as callback for the 'port rename' event. +
The callback is executed as *_func(client, portname, newname)_*, where _portname_ is
the old (full) name of the affected port and _newname_ is its newly assigned name.#


[[jack.port_connect_callback]]
* *jack.port_connect_callback* ( _client_, _func_ ) _M_ +
[small]#Registers _func_ as callback for the 'ports connect or disconnect' event. +
The callback is executed as *_func(client, srcname, dstname, operation)_*, where 
_srcname_ and _dstname_ are the (full) names of the affected ports, and _operation_
is a string that may be either _'connected'_ or _'disconnected'_.#


[[jack.graph_order_callback]]
* *jack.graph_order_callback* ( _client_, _func_ ) _M_ +
[small]#Registers _func_ as callback for the 'graph reorder' event. +
The callback is executed as *_func(client)_*.#


[[jack.xrun_callback]]
* *jack.xrun_callback* ( _client_, _func_ ) _M_ +
[small]#Registers _func_ as callback for the 'xrun' event. +
The callback is executed as *_func(client)_*.#


[[jack.latency_callback]]
* *jack.latency_callback* ( _client_, _func_ ) _M_ +
[small]#Registers _func_ as callback for the 'latency recomputations needed' event. +
The callback is executed as *_func(client, mode)_*, where _mode_ is a string that
may be either _'capture'_ or _'playback'_.#


[[jack.session_callback]]
* *jack.session_callback* ( _client_, _func_ ) _M_ +
[small]#Registers _func_ as callback for the 'session notification' event. +
The callback is executed as
*_command, flag1, flag2 = func(client, type, path, uuid)_*, 
where: +
_type_ (a string) is the type of this session event and may be one of _'save'_, 
_'save_and_quit'_ or _'save_template'_; +
_path_ (a string) is the session directory path; +
_uuid_ (a string) is the client UUID which must be used when opening the client. +
The callback is expected to return the following values, which are used by LuaJack to
reply to the event: +
_command_: the command line (a string) needed to restore the client; +
_flag1_, _flag2_: optional session flags (_'save_error'_ and/or _'need_terminal'_).#

