
== Ports

Instead of a single port_register() function, LuaJack provides a few functions to
create ports depending on the desired direction (_input_ or _output_) and port type 
(default _audio_, default _midi_, or _custom_, i.e. not built-in).
These port-creating functions are listed below, followed by the functions for port handling.

Notice that most of the port-handling functions are available in two versions: 
the version named *jack.port_xxx* acts on a port by reference, is usually faster
because it does not involve querying the server to resolve the port name, but can be
used only in the application that created the port; the version named *jack.nport_xxx*, 
on the other side, is slower because it acts on the port by its name, but it can be used
also on ports not created by the invoking application.

'''
[[jack.input_audio_port]]
* *jack.input_audio_port* ( _client_ , _name_ [, _options_ ] ) +
-> _port_ +
 +
Creates an input port of the default audio type for _client_ and returns a reference
for subsequent operations. +
 +
The mandatory _name_ argument (a string) is the short name to be assigned to the port, while 
the _options_ parameter, if present, must be a table with zero or more of the following
elements: +
- _options.is_physical_ (boolean): JackPortIsPhysical flag; +
- _options.can_monitor_ (boolean): JackPortCanMonitor flag; +
- _options.is_terminal_ (boolean): JackPortIsTerminal flag.

////
@@TODO custom ports
- _options.port_type_ (string): port type name, mandatory for custom type ports;
- _options.buffer_size_ (integer): port buffer size, mandatory for custom type ports.
////

'''
[[jack.output_audio_port]]
* *jack.output_audio_port* ( _client_ , _name_ [, _options_ ] ) +
-> _port_ +
 +
Creates an output port of the default audio type 
for _client_ and returns a reference for subsequent operations. +
The meaning of the arguments is the same as for <<jack.input_audio_port, jack.input_audio_port>>().

'''
[[jack.input_midi_port]]
* *jack.input_midi_port* ( _client_ , _name_ [, _options_ ] ) +
-> _port_ +
 +
Creates an input port of the default MIDI type 
for _client_ and returns a reference for subsequent operations. +
The meaning of the arguments is the same as for <<jack.input_audio_port, jack.input_audio_port>>().

'''
[[jack.output_midi_port]]
* *jack.output_midi_port* ( _client_ , _name_ [, _options_ ] ) +
-> _port_ +
 +
Creates an output port of the default MIDI type 
for _client_ and returns a reference for subsequent operations. +
The meaning of the arguments is the same as for <<jack.input_audio_port, jack.input_audio_port>>().

//^@@TODO custom ports ---------------------------------------------------------
'''
[[jack.input_custom_port]]
* *jack.input_custom_port* ( _client_ , _name_ [, _options_ ] ) +
-> _port_ +
 +
Not available yet.

'''
[[jack.output_custom_port]]
* *jack.output_custom_port* ( _client_ , _name_ [, _options_ ] ) +
-> _port_ +
 +
Not available yet.
//^-----------------------------------------------------------------------------

'''
[[jack.port_name_size]]
* *jack.port_name_size* ( ) +
-> _maxsize_ +
 +
Returns the maximum allowed size for JACK port names.

'''
[[jack.port_type_size]]
* *jack.port_type_size* ( ) +
-> _maxsize_ +
 +
Returns the maximum allowed size for JACK port types.


'''
[[jack.port_unregister]]
* *jack.port_unregister* ( _port_ ) +
 +
Unregisters and deletes _port_.

NOTE: A port is automatically unregistered by LuaJack when the client that created it is 
<<jack.client_close, closed>>.

////
'''
[[jack.port_by_name]]
* *jack.port_by_name* ( _client_, _portname_ ) +
-> _port_ +
 +
Returns the _port_ object for the port whose full name is _portname_, or _nil_
if not found.
This function can be used only by the _client_ that created the port.
////

'''
[[jack.connect]]
* *jack.port_connect* ( _port_, _portname2_ ) +
* *jack.nport_connect* ( _client_, _portname1_, _portname2_ ) alias *jack.connect* +
 +
Connects two ports. One of the two ports must be an output port (source of the connection)
and the other must be an input port (destination). The two ports can be passed in any order.


'''
[[jack.disconnect]]
* *jack.port_disconnect* ( _port_ [, _portname2_] ) +
* *jack.nport_disconnect* ( _client_, _portname1_ [, _portname2_] )  alias *jack.disconnect* +
 +
Disconnects two ports. 
If _portname2_ is _nil_, the first port is disconnected from all the ports it is connected to.

'''
[[jack.port_name]]
* *jack.port_name* ( _port_ ) +
-> _fullname_ +
 +
Returns the port's full name.

'''
[[jack.port_short_name]]
* *jack.port_short_name* ( _port_ ) +
-> _shortname_ +
 +
Returns the port's short name.

////
DEPRECATED
'''
[[jack.port_set_name]]
* *jack.port_set_name* ( _port_, _newname_ ) +
 +
Changes the port's short name to _newname_.
////

'''
[[jack.port_flags]]
* *jack.port_flags* ( _port_ ) +
* *jack.nport_flags* ( _client_, _portname_ ) +
-> _flags_, _table_ +
 +
Returns the port's flags, in two equivalent formats: +
[circle]
- _flags_ : a string concatenating the flags that apply to the port, and
- _table_: a table where _table.<flag>_ is _true_ if _<flag>_ applies to the port,
or _nil_ otherwise.
 +
(_<flag>_ = _'input'_ | _'output'_ | _'audio'_ | _'midi'_ | _'custom'_ |
_'is_physical'_ | _'can_monitor'_ | _'is_terminal'_ )


'''
[[jack.port_uuid]]
* *jack.port_uuid* ( _port_ ) +
* *jack.nport_uuid* ( _client_, _portname_ ) +
-> _uuid_ +
 +
Returns the port's UUID (a string), or _nil_ if not found.

'''
[[jack.port_type]]
* *jack.port_type* ( _port_ ) +
* *jack.nport_type* ( _client_, _portname_ ) +
-> _type_ +
 +
Returns the port's type (a string), or _nil_ if not found.

'''
[[jack.nport_exists]]
* *jack.nport_exists* ( _client_, _portname_ ) +
-> _boolean_ +
 +
Returns _true_ if the port with the full named _portname_ exists, otherwise it returns _false_.

'''
[[jack.port_is_mine]]
* *jack.port_is_mine* ( _client_, _port_ ) +
* *jack.nport_is_mine* ( _client_, _portname_ ) +
-> _boolean_ +
 +
Returns _true_ if the port is owned by the invoking _client_, otherwise it returns _false_.

'''
[[jack.port_set_alias]]
* *jack.port_set_alias* ( _port_, _alias_ ) +
* *jack.nport_set_alias* ( _client_, _portname_, _alias_ ) +
 +
Sets _alias_ as an alias for the port.

'''
[[jack.port_unset_alias]]
* *jack.port_unset_alias* ( _port_, _alias_ ) +
* *jack.nport_unset_alias* ( _client_, _portname_, _alias_ ) +
 +
Unsets _alias_ as an alias for the port.

'''
[[jack.port_aliases]]
* *jack.port_aliases* ( _port_ ) +
* *jack.nport_aliases* ( _client_, _portname_ ) +
-> _alias1_, _alias2_ +
 +
Returns the aliases for the port (if it has any).

'''
[[jack.port_connections]]
* *jack.port_connections* ( _port_ [, _list_ ] ) +
* *jack.nport_connections* ( _client_, _portname_ [, _list_ ] ) +
-> _N_, _{ portname1, ..., portnameN }_ +
 +
Returns the number of connections the port is involved in. If _list = true_, it returns also
a table containing the full names of the ports the port is connected to.

'''
[[jack.port_connected_to]]
* *jack.port_connected_to* ( _port_, _portname2_ ) +
* *jack.nport_connected_to* ( _client_, _portname1_, _portname2_ ) +
-> _boolean_ +
 +
Returns _true_ if the two ports are connected, _false_ otherwise.

'''
[[jack.port_monitor]]
* *jack.port_monitor* ( _port_, _onoff_ ) +
* *jack.nport_monitor* ( _client_, _portname_, _onoff_ ) +
 +
Turns input monitoring on or off for the port (implemented with jack_port_ensure_monitor()).
The _onoff_ argument is a string and may be _'on'_ or _'off_.

'''
[[jack.port_monitoring]]
* *jack.port_monitoring* ( _port_ ) +
* *jack.nport_monitoring* ( _client_, _portname_ ) +
-> _boolean_ +
 +
Returns _true_ if input monitoring has been requested for the port, _false_ otherwise
or if no port with this name was found.

////
@@TODO size = port_type_buffer_size(client, port_type)
  (may only be called in a BufferSize callback)
////

'''
[[jack.get_ports]]
* *jack.get_ports* ( _client_ [, _filter_ ]) +
-> _{ portname1, ..., portnameN }_ +
 +
Returns a list (table) of full port names. If _filter_ is _nil_, all the ports are listed,
otherwise the ports are selected according to the _filter_ parameter, which must be a table
containing zero or more of the following optional elements: +
- _filter.name_pattern_: a regular expression (string) used to select ports by name;
- _filter.type_pattern_: a regular expression (string) used to select ports by type;
- _filter.direction_: a string that may be _'input'_ or _'output'_, to select input ports only 
or output ports only, respectively;
- _filter.is_physical_ (boolean): if _true_, list only physical ports;
- _filter.can_monitor_ (boolean): if _true_, list only ports that can monitor; 
- _filter.is_terminal_ (boolean): if _true_, list only terminal ports.


<<<
