
== Preface

This is the reference manual of *LuaJack*, which is a 
http://www.lua.org[*Lua*] binding library for the 
http://jackaudio.org[*JACK Audio Connection Kit*]. 
footnote:[
This manual is written in
http://www.methods.co.nz/asciidoc/[AsciiDoc], rendered with
http://asciidoctor.org/[AsciiDoctor] and a CSS from the
https://github.com/asciidoctor/asciidoctor-stylesheet-factory[AsciiDoctor Stylesheet Factory].
The PDF version is produced with
https://github.com/asciidoctor/asciidoctor-pdf[AsciiDoctor-Pdf].]

It is assumed that the reader is familiar with both JACK and the Lua programming language.

For convenience of reference, this document contains external (deep) links to the 
http://www.lua.org/manual/5.3/manual.html[Lua Reference Manual] and to the 
http://jackaudio.org/api/[JACK API documentation].
 
=== Getting and installing

For installation intructions, refer to the README file in the 
https://github.com/stetre/luajack[*LuaJack official repository*]
on GitHub.

////
The *official repository* of LuaJack is on GitHub at the following link:
*https://github.com/stetre/luajack* .

LuaJack runs on GNU/Linux and requires 
*http://www.lua.org[Lua]* version 5.3 or greater, and
*http://jackaudio.org[JACK]* (aligned to JACK API v0.124.1).

By now, it has been used only on GNU/Linux Fedora 21 with JACK2 v1.9.10.
It should compile and run also on any other GNU/Linux distribution and with
JACK1 instead of JACK2, but this has not been tested.

To install LuaJack, download the 
https://github.com/stetre/luajack/releases[latest release] and do the following:

[source,shell]
----
# ... download luajack-0.1.tar.gz ...
[ ]$ tar -zxpvf luajack-0.1.tar.gz
[ ]$ cd luajack-0.1
[luajack-0.1]$ make
[luajack-0.1]$ make check
[luajack-0.1]$ sudo make install
----

The _$make check_ command shows you what will be installed and where (please read
its output before executing _$make install_).
By default, LuaJack installs its components in subdirectories of `/usr/local/`
(and creates such directories, if needed).
This behaviour can be changed by defining PREFIX with the desired alternative 
base installation directory. For example, this will install the components
in `/home/joe/local`:

[source,shell]
----
[luajack-0.1]$ make
[luajack-0.1]$ make install PREFIX=/home/joe/local
----
////

=== Module organization

The LuaJack module is loaded using Lua's 
http://www.lua.org/manual/5.3/manual.html#pdf-require[require]() and
returns a table containing the functions it provides 
(as usual with Lua modules). This manual assumes that such
table is named *jack*, i.e. that it is loaded with:

[source,lua,indent=1]
----
jack = require("luajack")
----

but nothing forbids the use of a different name.

=== Examples

A few examples can be found in the *examples/* directory of the release package
(some of them are LuaJack versions of the examples that come with the original JACK1
and JACK2 software).

=== License

LuaJack is released under the *MIT/X11 license* (same as
http://www.lua.org/license.html[Lua], and with the same only requirement to give proper
credits to the original author). 
The copyright notice is in the LICENSE file in the base directory
of the https://github.com/stetre/luajack[official repository] on GitHub.

<<<
